# Generated by Django 6.0.6 on 2026-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_state_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(default='', upload_to='media/user/avatar'),
            preserve_default=False,
        ),
    ]
