# Generated by Django 5.2.8 on 2026-07-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_author_id_alter_book_id_alter_character_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=True, verbose_name='Здоровье'),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=True, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='character',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.state'),
        ),
    ]
