# Generated by Django 5.2.8 on 2026-07-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_character_hp_character_speed_alter_character_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='state',
        ),
    ]
